INHERIT: docs/common/config.yml

site_description: "sfizz wiki"
site_name: "sfizz-wiki"
site_url: "https://sfz.tools/sfizz-wiki"

#copyright: "Copyright &copy; 2019-2023 SFZTools Organization"

repo_name: "GitHub"
repo_url: "https://github.com/sfztools/sfizz-wiki"

extra:
  homepage: "/"
  copyright_auto: true
  copyright_since: 2019
  site_owner: "SFZTools Organization"
  social:
  - icon: "fontawesome/brands/github"
    link: "https://github.com/sfztools/sfizz/"
    name: "sfizz on GitHub"

  - icon: "fontawesome/solid/hashtag"
    link: "https://kiwiirc.com/nextclient/#irc://irc.libera.chat:+6697/#sfztools"
    name: "sfizz on IRC"

  - icon: "fontawesome/brands/discord"
    link: "https://discord.gg/3ArE9Mw"
    name: "sfizz on Discord"

  - icon: "fontawesome/solid/at"
    link: "https://sfz.tools/sfizz-wiki/contacts"
    name: "EMail"

  - icon: "fontawesome/solid/rss"
    link: "https://sfz.tools/atom.xml"
    name: "News Atom Feed"

nav:
- External Links:
  - "SFZ Format": "https://sfzformat.com/"
  - "SFZ Instruments": "https://github.com/sfzinstruments/"
  - "FreePats Instruments": "https://freepats.zenvoid.org/"
  - "LinuxAudio": "https://linuxaudio.org/"
  - "LinuxMAO": "https://linuxmao.org/"
- "index.md"
- "contacts.md"
- Developer notes:
  - "Filters.md"
  - "Resampling.md"
  - "OBS-builds.md"
  - "Rolling-out-new-versions.md"
  - "To-deprecate-on-next-API-ABI-break.md"
- Analysis:
  - "Effect-routing.md"
  - "Effects.md"
  - "Curves.md"
  - "EQ-and-filters.md"
- Project Perspective / WIP:
  - "Ideas-for-longer-term.md"
  - "UI-themes.md"
